# -*- coding: utf-8 -*-
"""CTD_prework_CCampbell.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x-UI61q8FqUC5Iw1snt4vUvCsqEGa2V
"""

# Description: This script asks the user for their preferred clothing item
# and the current outdoor temperature in Fahrenheit. It then recommends
# an outfit based on the temperature.

# Get two inputs from the user and store each in its own variable
clothing_item = input("What is your favorite item of clothing to wear? ")
temperature_str = input("What is the current outdoor temperature in °F? ")

# Convert the temperature input into an integer (using a number)
temperature = int(temperature_str)

# Conditional statement testing one of the user's inputs
if temperature >= 65:
    recommendation = "It's nice and warm outside!"
else:
    recommendation = "It's a bit chilly, so grab a jacket!"

# Print statement that uses both user variables
print(f"You chose your {clothing_item}. {recommendation} At {temperature}°F, make sure you're comfortable!")

# EXAMPLE RUN 1:
#Input Hoodie
#Output It's a bit chilly, so grab a jacket!
#Input 52
#Output make sure you're comfortable!

#EXAMPLE RUN 2:
#Input sunglasses
#Output It's nice and warm outside!
#Input 65
#Output make sure you're comfortable!